separator=false
markup=pango
separator_block_width=10

[blur_lock]
command=~/.config/i3/scripts/blur-lock
interval=once

[browser]
full_text=  
color=#ff7f81
command=i3-msg -q exec firefox

[jupyter]
color=#ff7f81
command=~/.config/dotfiles/run_notebook.sh
interval=1

[emacs]
full_text= Emacs 
#color=#7F5AB6
markup=pango
command=i3-msg -q exec emacs

[code]
full_text=󰨞
color=#007ACC
command=i3-msg -q exec code

[files]
full_text=  
color=#7f3fbf
command=i3-msg -q exec thunar ~/

[disk]
label= 
instance=/
command=~/.config/i3/scripts/disk.sh
interval=30

[memory]
label= 
command=~/.config/i3/scripts/memory
interval=2

[cpu_usage]
label= 
command=~/.config/i3/scripts/cpu_usage.sh
#min_width=CPU: 100.00%
interval=2

[CPU-temperature]
label=
command=~/.config/i3/scripts/temperature
interval=30

[pavucontrol]
full_text= 
command=pavucontrol

[volume-pulseaudio]
command=~/.config/i3/scripts/volume
instance=Master
interval=1

#Show the current power-profile
[ppd-status]
command=~/.config/i3/scripts/ppd-status
interval=5

[monitors]
full_text=
command=~/.config/i3/scripts/monitores.sh
interval=once

[time]
#label=    
command=date '+%a %d %b %H:%M:%S'
interval=1
min_width=170
align=center

[shutdown_menu]
full_text= 
command=~/.config/i3/scripts/powermenu_wrapper.sh
interval=once
signal=10
align=center


